version: '3.8'
services:
  dev-db:
    container_name: 'test-postgres'
    restart: unless-stopped
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
